<a href="https://colab.research.google.com/github/JongeunKeum/python-numpy/blob/main/Section01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# Section 1. N차원 배열 생성

## 1-1. N차원 배열(ndarray) 생성하기

In [7]:
# 1차원 배열
arr = np.array([1, 2, 3])
print(arr)

# 2차원 배열
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [11]:
type([1, 2, 3])

list

In [12]:
type(arr)

numpy.ndarray

In [13]:
tpl = (4, 5, 6)
arr = np.array(tpl)
print(arr)

[4 5 6]


In [15]:
lst = [1, 2, 3]
arr = np.array(lst)
print(arr)

[1 2 3]


In [16]:
lst2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(lst2)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [19]:
# shape
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1.shape, arr2.shape) # arr1은 원소가 3개인 1차원 배열, arr2는 행이 2개, 열이 3개인 2차원 array

(3,) (2, 3)


In [20]:
# ndim 차원 표시
print(arr1.ndim, arr2.ndim)

1 2


In [22]:
# size 원소 개수
print(arr1.size, arr2.size)

3 6


## 1-2. N차원 배열의 데이터 타입

In [26]:
arr = np.array([1, 2, 3], dtype=float)
print(arr, arr.dtype)

[1. 2. 3.] float64


In [27]:
arr = np.array([1, 2, 3], dtype=int)
print(arr, arr.dtype)

[1 2 3] int64


In [28]:
arr = np.array([0, 1, 1], dtype=bool)
print(arr, arr.dtype)

[False  True  True] bool


In [31]:
arr = np.array([0, 1, 2 ,3])
print(arr, arr.dtype)

arr = arr.astype(np.float32)
print(arr, arr.dtype)

[0 1 2 3] int64
[0. 1. 2. 3.] float32


In [33]:
# 데이터 타입이 혼재하는 경우
arr = np.array([1, 2, 3.4])
print(arr, arr.dtype)
# 타입을 섞어서 넣었더니 모두 float64로 바뀌어서 출력됨

[1.  2.  3.4] float64


In [38]:
#arr = np.array([1, 2, 3.4, "string"], dtype=int)
#print(arr, arr.dtype)
# 문자열을 int로 변환할 수 없어서 에러 발생

## 1-3. 정해진 형식의 N차원 배열 생성하기

In [40]:
# np.zeros() 모든 원소가 0으로 된 배열 생성
arr = np.zeros([2, 2]) # 인자로 shape 입력
print(arr)

[[0. 0.]
 [0. 0.]]


In [41]:
# np.ones() 모든 원소가 1로 된 배열 생성
arr = np.ones([3, 5])
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [42]:
# np.full() 모든 원소가 지정된 값으로 이루어진 배열 생성
arr = np.full((2, 3), 5)
print(arr)

[[5 5 5]
 [5 5 5]]


In [51]:
# np.eye() 행을 n, 열을 m이라고 했을 때, n*m 행렬에서 대각선 원소가 1인 배열 생성(n값만 주면 정방행렬 생성)
arr = np.eye(3, 4)
print("arr")
print(arr)

arr2 = np.eye(3, 4, k=1) # k값은 대각원소의 발생지점 지정 가능
print("arr2")
print(arr2)

arr3 = np.eye(3, 4, k=-1)
print("arr3")
print(arr3)

arr
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
arr2
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
arr3
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [54]:
# 지정된 행렬과 동일한 shape을 갖도록 함
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# np.zeros_like()
arr_z = np.zeros_like(arr)
print("zeros_like")
print(arr_z)

# np.ones_like()
arr_o = np.ones_like(arr)
print("ones_like")
print(arr_o)

# np.full_like()
arr_f = np.full_like(arr, 9)
print("full_like")
print(arr_f)

zeros_like
[[0 0 0]
 [0 0 0]]
ones_like
[[1 1 1]
 [1 1 1]]
full_like
[[9 9 9]
 [9 9 9]]


## 1-4. 특정 범위의 값을 가지는 N차원 배열 생성하기

In [55]:
lst = list(range(0, 9, 2))
print(lst)

[0, 2, 4, 6, 8]


In [62]:
# np.arange()
arr = np.arange(9)
print(arr)

[0 1 2 3 4 5 6 7 8]


In [63]:
arr = np.arange(3, 12) # stop 값 미만
print(arr)

[ 3  4  5  6  7  8  9 10 11]


In [64]:
arr = np.arange(3, 13, 3)
print(arr)

[ 3  6  9 12]


In [65]:
arr = np.arange(stop=9, step=2, start=0) # np.arange(0, 9, 2)
print(arr)

[0 2 4 6 8]


In [67]:
# np.linspace()
arr = np.linspace(0, 100, 11) # 0~100 사이의 11개의 원소를 균등한 간격으로 출력. stop 값 이하
print(arr)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [68]:
arr = np.linspace(0, 100, 250)
print(arr)

[  0.           0.40160643   0.80321285   1.20481928   1.6064257
   2.00803213   2.40963855   2.81124498   3.21285141   3.61445783
   4.01606426   4.41767068   4.81927711   5.22088353   5.62248996
   6.02409639   6.42570281   6.82730924   7.22891566   7.63052209
   8.03212851   8.43373494   8.83534137   9.23694779   9.63855422
  10.04016064  10.44176707  10.84337349  11.24497992  11.64658635
  12.04819277  12.4497992   12.85140562  13.25301205  13.65461847
  14.0562249   14.45783133  14.85943775  15.26104418  15.6626506
  16.06425703  16.46586345  16.86746988  17.26907631  17.67068273
  18.07228916  18.47389558  18.87550201  19.27710843  19.67871486
  20.08032129  20.48192771  20.88353414  21.28514056  21.68674699
  22.08835341  22.48995984  22.89156627  23.29317269  23.69477912
  24.09638554  24.49799197  24.89959839  25.30120482  25.70281124
  26.10441767  26.5060241   26.90763052  27.30923695  27.71084337
  28.1124498   28.51405622  28.91566265  29.31726908  29.7188755
  30.12048193

In [69]:
# np.logspace() log값 스케일의 linspace 메소드
arr = np.linspace(1, 10, 10)
print(arr, end="\n\n")

arr = np.logspace(1, 10, 10, base=2) # base는 log의 밑
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [71]:
arr = np.logspace(1, 10, 10) # base를 지정하지 않으면 상용로그 사용
print(arr)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]
