<a href="https://colab.research.google.com/github/JongeunKeum/python-numpy/blob/main/Section06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Section 6. N차원 배열의 병합

## 6-1. 배열에 원소 추가 및 삭제

In [2]:
# python list
arr = [1, 2, 3, 4, 5, 6, 7, 8]
arr.insert(2, 50)
print(arr)

[1, 2, 50, 3, 4, 5, 6, 7, 8]


In [3]:
# 1차원 배열 insert()
arr = np.arange(1, 9)
arr = np.insert(arr, 2, 50)
print(arr)

[ 1  2 50  3  4  5  6  7  8]


In [4]:
# 2차원 배열 insert()
arr = np.arange(1, 13).reshape(3, 4)
arr = np.insert(arr, 2, 50, axis=0)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [50 50 50 50]
 [ 9 10 11 12]]


In [5]:
arr = np.arange(1, 13).reshape(3, 4)
arr = np.insert(arr, 2, 50, axis=1)
print(arr)

[[ 1  2 50  3  4]
 [ 5  6 50  7  8]
 [ 9 10 50 11 12]]


In [7]:
arr = np.arange(1, 13).reshape(3, 4)
arr = np.insert(arr, 2, 50) # axis 값을 주지 않으면, 1차원 배열로 변환 후에 삽입함
print(arr)

[ 1  2 50  3  4  5  6  7  8  9 10 11 12]


In [9]:
# delete()
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

arr = np.delete(arr, 2, axis=0)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]


In [10]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

arr = np.delete(arr, 2, axis=1)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]]


In [11]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

arr = np.delete(arr, 2)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  4  5  6  7  8  9 10 11 12]


## 6-2. 배열 간의 병합

In [15]:
# append()
arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(13, 25).reshape(3, 4)

print(arr1)
print(arr2, end="\n\n")

# axis=0
arr3 = np.append(arr1, arr2, axis=0)
print(arr3, end="\n\n")

# axis=1
arr4 = np.append(arr1, arr2, axis=1)
print(arr4, end="\n\n")

# axis 값 없이
arr5 = np.append(arr1, arr2)
print(arr5, end="\n\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]



In [18]:
# vstack(): axis=0으로 병합, hstack(): axis=1로 병합
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(7, 13).reshape(2, 3)

arr3 = np.vstack((arr1, arr2))
print(arr3, end="\n\n")

arr4 = np.hstack((arr1, arr2))
print(arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [21]:
# concatenate()
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(7, 13).reshape(2, 3)

arr3 = np.concatenate([arr1, arr2], axis=0)
print(arr3, end="\n\n")

arr4 = np.concatenate([arr1, arr2], axis=1)
print(arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## 6-3. 배열 분할

In [22]:
# 2차원 배열
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
# vsplit(): axis=0으로 분할
arr_v = np.vsplit(arr, 3) # arr의 행이 3개이므로 홀수개로만 분할 가능
print(arr_v)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


In [25]:
# hsplit(): axis=1로 분할
arr_h = np.hsplit(arr, 2) # arr의 열이 4개이므로 짝수개로만 분할 가능
print(arr_h)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [26]:
# 3차원 배열
arr = np.random.randint(0, 10, (4, 6, 8))
print(arr)

[[[7 9 4 0 9 8 9 0]
  [2 0 4 6 6 8 1 0]
  [4 3 4 9 4 0 2 5]
  [8 8 0 1 4 8 5 8]
  [1 3 9 1 3 9 0 2]
  [5 6 8 6 9 0 7 2]]

 [[0 5 7 8 4 6 3 6]
  [8 9 2 0 6 3 8 9]
  [8 2 0 8 6 3 7 7]
  [1 9 4 9 8 0 5 4]
  [1 9 4 2 8 1 3 9]
  [9 3 9 6 8 1 2 6]]

 [[4 9 0 5 2 2 4 8]
  [5 6 4 4 9 4 7 5]
  [8 4 4 2 6 2 5 9]
  [7 5 8 3 6 7 2 0]
  [3 4 9 8 6 7 4 3]
  [9 0 0 9 9 6 4 3]]

 [[1 9 7 8 8 7 6 4]
  [0 6 5 7 8 4 4 7]
  [7 6 4 8 0 3 3 2]
  [3 4 2 5 5 2 1 2]
  [1 1 7 4 4 9 8 8]
  [2 1 8 5 5 0 2 8]]]


In [27]:
arr_v = np.vsplit(arr, 2)
print(arr_v)

[array([[[7, 9, 4, 0, 9, 8, 9, 0],
        [2, 0, 4, 6, 6, 8, 1, 0],
        [4, 3, 4, 9, 4, 0, 2, 5],
        [8, 8, 0, 1, 4, 8, 5, 8],
        [1, 3, 9, 1, 3, 9, 0, 2],
        [5, 6, 8, 6, 9, 0, 7, 2]],

       [[0, 5, 7, 8, 4, 6, 3, 6],
        [8, 9, 2, 0, 6, 3, 8, 9],
        [8, 2, 0, 8, 6, 3, 7, 7],
        [1, 9, 4, 9, 8, 0, 5, 4],
        [1, 9, 4, 2, 8, 1, 3, 9],
        [9, 3, 9, 6, 8, 1, 2, 6]]]), array([[[4, 9, 0, 5, 2, 2, 4, 8],
        [5, 6, 4, 4, 9, 4, 7, 5],
        [8, 4, 4, 2, 6, 2, 5, 9],
        [7, 5, 8, 3, 6, 7, 2, 0],
        [3, 4, 9, 8, 6, 7, 4, 3],
        [9, 0, 0, 9, 9, 6, 4, 3]],

       [[1, 9, 7, 8, 8, 7, 6, 4],
        [0, 6, 5, 7, 8, 4, 4, 7],
        [7, 6, 4, 8, 0, 3, 3, 2],
        [3, 4, 2, 5, 5, 2, 1, 2],
        [1, 1, 7, 4, 4, 9, 8, 8],
        [2, 1, 8, 5, 5, 0, 2, 8]]])]


In [28]:
arr_h = np.hsplit(arr, 2)
print(arr_h)

[array([[[7, 9, 4, 0, 9, 8, 9, 0],
        [2, 0, 4, 6, 6, 8, 1, 0],
        [4, 3, 4, 9, 4, 0, 2, 5]],

       [[0, 5, 7, 8, 4, 6, 3, 6],
        [8, 9, 2, 0, 6, 3, 8, 9],
        [8, 2, 0, 8, 6, 3, 7, 7]],

       [[4, 9, 0, 5, 2, 2, 4, 8],
        [5, 6, 4, 4, 9, 4, 7, 5],
        [8, 4, 4, 2, 6, 2, 5, 9]],

       [[1, 9, 7, 8, 8, 7, 6, 4],
        [0, 6, 5, 7, 8, 4, 4, 7],
        [7, 6, 4, 8, 0, 3, 3, 2]]]), array([[[8, 8, 0, 1, 4, 8, 5, 8],
        [1, 3, 9, 1, 3, 9, 0, 2],
        [5, 6, 8, 6, 9, 0, 7, 2]],

       [[1, 9, 4, 9, 8, 0, 5, 4],
        [1, 9, 4, 2, 8, 1, 3, 9],
        [9, 3, 9, 6, 8, 1, 2, 6]],

       [[7, 5, 8, 3, 6, 7, 2, 0],
        [3, 4, 9, 8, 6, 7, 4, 3],
        [9, 0, 0, 9, 9, 6, 4, 3]],

       [[3, 4, 2, 5, 5, 2, 1, 2],
        [1, 1, 7, 4, 4, 9, 8, 8],
        [2, 1, 8, 5, 5, 0, 2, 8]]])]
