<a href="https://colab.research.google.com/github/JongeunKeum/python-numpy/blob/main/Section05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Section 5. N차원 배열의 형태 변경

## 5-1. 배열의 형태 변경 1: reshape()

In [3]:
arr = np.arange(12)
print(arr, arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 1


In [5]:
arr = arr.reshape((3, 4))   # 원소의 개수가 맞아야 함
print(arr, arr.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2


In [7]:
arr = arr.reshape((2, 3, 2))
print(arr, arr.ndim)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 3


In [8]:
arr = arr.reshape((2, 2, 1, 3))
print(arr, arr.ndim)

[[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]] 4


### Curse of Dimensionality (차원의 저주)

차원이 증가하면서 학습 데이터 수가 차원의 수보다 적어지면서 모델의 성능이 저하되는 현상