<a href="https://colab.research.google.com/github/JongeunKeum/python-numpy/blob/main/Section01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# Section 1. N차원 배열 생성

## 1-1. N차원 배열(ndarray) 생성하기

In [7]:
# 1차원 배열
arr = np.array([1, 2, 3])
print(arr)

# 2차원 배열
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [11]:
type([1, 2, 3])

list

In [12]:
type(arr)

numpy.ndarray

In [13]:
tpl = (4, 5, 6)
arr = np.array(tpl)
print(arr)

[4 5 6]


In [15]:
lst = [1, 2, 3]
arr = np.array(lst)
print(arr)

[1 2 3]


In [16]:
lst2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(lst2)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [19]:
# shape
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1.shape, arr2.shape) # arr1은 원소가 3개인 1차원 배열, arr2는 행이 2개, 열이 3개인 2차원 array

(3,) (2, 3)


In [20]:
# ndim 차원 표시
print(arr1.ndim, arr2.ndim)

1 2


In [22]:
# size 원소 개수
print(arr1.size, arr2.size)

3 6
