<a href="https://colab.research.google.com/github/JongeunKeum/python-numpy/blob/main/Section03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Section 3. N차원 배열 연산법

## 3-1. 배열의 연산 1: 사칙연산/제곱/제곱근/몫/나머지

In [2]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
arr2 = np.full((3, 3), 2)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [4]:
# 덧셈
print(arr1 + arr2)
print(np.add(arr1, arr2))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [6]:
# 뺄셈
print(arr1 - arr2)
print(np.subtract(arr1, arr2))

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [8]:
# 곱셈(내적이 아님. 원소 단위의 곱셈 결과)
print(arr1 * arr2)
print(np.multiply(arr1, arr2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [9]:
# 나눗셈
print(arr1 / arr2)
print(np.divide(arr1, arr2))

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [10]:
# 제곱
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
arr2 = np.full((3, 3), 2)

print(arr1 ** 5)
print(np.square(arr1))

[[    1    32   243]
 [ 1024  3125  7776]
 [16807 32768 59049]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [11]:
# 제곱근
print(np.sqrt(arr1))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [13]:
# 몫
print(arr1 // arr2)

[[0 1 1]
 [2 2 3]
 [3 4 4]]


In [15]:
# 나머지
print(arr1 % arr2)

[[1 0 1]
 [0 1 0]
 [1 0 1]]


## 3-2. 배열의 연산 2: 내적(dot product)/절대값/올림/내림/반올림/버림

In [17]:
# 1차원 행렬 내적
arr1 = np.array([2, 3, 4])
arr2 = np.array([1, 2, 3])

print(np.dot(arr1, arr2))

20


In [18]:
# 2차원 행렬 내적
'''
[[a, b]      [[e, f]         [[ae + bg, af + bh]
 [c, d]]      [g, h]]   =>    [ce + dg, cf + dh]]
'''

arr1 = np.array([[1, 2],
                 [4, 5]])
arr2 = np.array([[1, 2],
                 [0, 3]])
print(np.dot(arr1, arr2))

[[ 1  8]
 [ 4 23]]


In [19]:
# 절대값
arr1 = np.array([[1, -2],
                 [-4, 5]])
print(np.abs(arr1))

[[1 2]
 [4 5]]


In [24]:
# 올림
arr = np.array([[1.932, -2.339],
                 [-4.145, 5.206]])
print(np.ceil(arr))

[[ 2. -2.]
 [-4.  6.]]


In [25]:
# 내림
print(np.floor(arr))

[[ 1. -3.]
 [-5.  5.]]


In [26]:
# 반올림
print(np.round(arr))

[[ 2. -2.]
 [-4.  5.]]


In [27]:
# 버림
print(np.trunc(arr))

[[ 1. -2.]
 [-4.  5.]]
