<a href="https://colab.research.google.com/github/JongeunKeum/python-numpy/blob/main/Section03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Section 3. N차원 배열 연산법

## 3-1. 배열의 연산 1: 사칙연산/제곱/제곱근/몫/나머지

In [2]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
arr2 = np.full((3, 3), 2)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [4]:
# 덧셈
print(arr1 + arr2)
print(np.add(arr1, arr2))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [6]:
# 뺄셈
print(arr1 - arr2)
print(np.subtract(arr1, arr2))

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [8]:
# 곱셈(내적이 아님. 원소 단위의 곱셈 결과)
print(arr1 * arr2)
print(np.multiply(arr1, arr2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [9]:
# 나눗셈
print(arr1 / arr2)
print(np.divide(arr1, arr2))

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [10]:
# 제곱
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
arr2 = np.full((3, 3), 2)

print(arr1 ** 5)
print(np.square(arr1))

[[    1    32   243]
 [ 1024  3125  7776]
 [16807 32768 59049]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [11]:
# 제곱근
print(np.sqrt(arr1))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [13]:
# 몫
print(arr1 // arr2)

[[0 1 1]
 [2 2 3]
 [3 4 4]]


In [15]:
# 나머지
print(arr1 % arr2)

[[1 0 1]
 [0 1 0]
 [1 0 1]]


## 3-2. 배열의 연산 2: 내적(dot product)/절대값/올림/내림/반올림/버림

In [17]:
# 1차원 행렬 내적
arr1 = np.array([2, 3, 4])
arr2 = np.array([1, 2, 3])

print(np.dot(arr1, arr2))

20


In [18]:
# 2차원 행렬 내적
'''
[[a, b]      [[e, f]         [[ae + bg, af + bh]
 [c, d]]      [g, h]]   =>    [ce + dg, cf + dh]]
'''

arr1 = np.array([[1, 2],
                 [4, 5]])
arr2 = np.array([[1, 2],
                 [0, 3]])
print(np.dot(arr1, arr2))

[[ 1  8]
 [ 4 23]]


In [19]:
# 절대값
arr1 = np.array([[1, -2],
                 [-4, 5]])
print(np.abs(arr1))

[[1 2]
 [4 5]]


In [24]:
# 올림
arr = np.array([[1.932, -2.339],
                 [-4.145, 5.206]])
print(np.ceil(arr))

[[ 2. -2.]
 [-4.  6.]]


In [25]:
# 내림
print(np.floor(arr))

[[ 1. -3.]
 [-5.  5.]]


In [26]:
# 반올림
print(np.round(arr))

[[ 2. -2.]
 [-4.  5.]]


In [27]:
# 버림
print(np.trunc(arr))

[[ 1. -2.]
 [-4.  5.]]


## 3-3. 배열의 연산 3: min/max/sum/mean/std/cumsum/median

In [28]:
arr = np.array([[1, 2, 3],
                [0, 1, 4]])

In [32]:
# min(최소값)
print(np.min(arr))
print(arr.min())
print(arr.min(axis=0)) # 각 열에서 최소값
print(arr.min(axis=1)) # 각 행에서 최소값

0
0
[0 1 3]
[1 0]


In [34]:
# max(최대값)
print(np.max(arr))
print(arr.max())
print(arr.max(axis=0))
print(arr.max(axis=1))

4
4
[1 2 4]
[3 4]


In [39]:
# sum(원소의 합)
print(np.sum(arr))
print(arr.sum())
print(arr.sum(axis=0)) # 각 열의 합
print(arr.sum(axis=1)) # 각 행의 합

11
11
[1 3 7]
[6 5]


In [44]:
# mean(원소들의 평균값)
print(np.mean(arr))
print(arr.mean())
print(arr.mean(axis=0)) # 각 열의 평균
print(arr.mean(axis=1)) # 각 행의 평균

1.8333333333333333
1.8333333333333333
[0.5 1.5 3.5]
[2.         1.66666667]


In [48]:
# std(표준편차)
print(np.std(arr))
print(arr.std())
print(arr.std(axis=0))
print(arr.std(axis=1))

1.343709624716425
1.343709624716425
[0.5 0.5 0.5]
[0.81649658 1.69967317]


In [52]:
# cumsum(누적합)
arr = np.array([[1, 2, 3],
                [0, 1, 4]])

print(np.cumsum(arr)) # 1 출력 -> 1+2 출력 -> 1+2+3 출력 -> ... -> 1+2+3+0+1+4 출력
print(arr.cumsum())
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

[ 1  3  6  6  7 11]
[ 1  3  6  6  7 11]
[[1 2 3]
 [1 3 7]]
[[1 3 6]
 [0 1 5]]


In [57]:
# median(중앙값)(원소의 개수가 짝수일 때는 중앙값 2개의 사이값 반환)
arr = np.array([[1, 2, 3],
                [0, 1, 4],
                [1, 5, 2]])

print(np.median(arr))
print(np.median(arr, axis=0))
print(np.median(arr, axis=1))

2.0
[1. 2. 3.]
[2. 1. 2.]


## 3-4. 배열의 연산 4: 비교 연산/삼각 함수

In [62]:
# 비교 연산(같은 자리의 각 원소 간 비교)
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[1, 0, 3],
                 [4, -2, 9]])

print(arr1 == arr2)
print(arr1 > arr2)

[[ True False  True]
 [ True False False]]
[[False  True False]
 [False  True False]]


In [63]:
# 배열 전체가 동일한지 확인
print(np.array_equal(arr1, arr2))

False


In [67]:
# 삼각 함수
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# sin()
print(np.sin(arr))

# cos()
print(np.cos(arr))

# tan()
print(np.tan(arr))

# pi
print(np.pi)

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
3.141592653589793
