<a href="https://colab.research.google.com/github/JongeunKeum/python-numpy/blob/main/Section04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Section 4. N차원 배열 정렬

## 4-1. 1차원 배열의 정렬

In [2]:
arr = np.random.randint(10, size=10)
print(arr)

[5 4 6 4 0 0 8 5 7 6]


In [5]:
print(np.sort(arr))         # 오름차순
print(np.sort(arr)[::-1])   # 내림차순
# 이런 방법은 원본 배열이 변경되지 않음

[0 0 4 4 5 5 6 6 7 8]
[8 7 6 6 5 5 4 4 0 0]


In [7]:
# arr = np.sort(arr)    # 원본 배열 변경
arr.sort()            # 원본 배열 변경
print(arr)

[0 0 4 4 5 5 6 6 7 8]


## 4-2. 2차원 배열의 정렬

In [9]:
arr = np.random.randint(15, size=(3,4))
print(arr)

[[11 13 13 14]
 [13 14  3 12]
 [ 6 13 10  3]]


In [10]:
print(np.sort(arr))   # axis=1로 정렬됨

[[11 13 13 14]
 [ 3 12 13 14]
 [ 3  6 10 13]]


In [11]:
print(np.sort(arr, axis=0))

[[ 6 13  3  3]
 [11 13 10 12]
 [13 14 13 14]]


In [13]:
print(np.sort(arr, axis=None))  # 1차원 배열로 변환시킨 후에 오름차순으로 정렬

[ 3  3  6 10 11 12 13 13 13 13 14 14]


In [14]:
# argsort() 원소의 기존 위치를 나타냄
print(np.sort(arr, axis=1))
print(np.argsort(arr, axis=1)) 

[[11 13 13 14]
 [ 3 12 13 14]
 [ 3  6 10 13]]
[[0 1 2 3]
 [2 3 0 1]
 [3 0 2 1]]


In [16]:
print(np.sort(arr, axis=0))
print(np.argsort(arr, axis=0)) 

[[ 6 13  3  3]
 [11 13 10 12]
 [13 14 13 14]]
[[2 0 1 2]
 [0 2 2 1]
 [1 1 0 0]]
