<a href="https://colab.research.google.com/github/JongeunKeum/python-numpy/blob/main/Section02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Section 2. N차원 배열 인덱싱

## 2-1. 배열의 index 접근하기

In [3]:
# 1차원 배열
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(arr[3])
print(arr[1])
print(arr[-1])
print(arr[-3])

3
1
9
7


In [11]:
# 2차원 배열 인덱싱
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print(arr, arr.shape, arr.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 2


In [13]:
print(arr[0]) # 0행에 해당하는 값 전부

[1 2 3 4]


In [15]:
print(arr[0][3]) # 0행 3열
print(arr[0, 3])

4
4


In [23]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[3:8]) # 3부터 8 미만까지
print(arr[3:]) # 3부터 끝까지
print(arr[:7]) # 처음부터 7 미만까지
print(arr[:-1])

[3 4 5 6 7]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8]


In [25]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print(arr[0, :]) # 0행 모든 열
print(arr[:, 1]) # 모든 행 1열

[1 2 3 4]
[ 2  6 10]


In [27]:
print(arr[:3, :])
print(arr[:2, 2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]


## 2-2. 배열의 Fancy 인덱싱

In [28]:
# 1차원 배열
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr[[0, 2, 4]]) # 0번째, 2번째, 4번째 원소를 가져옴

[ 5 15 25]


In [30]:
# 2차원 배열
arr = np.array([[5, 10, 15, 20],
                [25, 30, 35, 40],
                [45, 50, 55, 60]])
print(arr[[0, 2], 2:]) # 0행과 2행, 2열부터 끝까지
print(arr[1:, [2, 3]]) # 1행부터 끝까지, 2열과 3열

[[15 20]
 [55 60]]
[[35 40]
 [55 60]]


## 2-3. 배열의 Boolean 인덱싱


In [31]:
arr = np.array([1, 2, 3, 4])
print(arr[[True, False, True, True]]) # True에 해당하는 값은 가져오고 False에 해당하는 값은 가져오지 않음

[1 3 4]


In [32]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
print(arr[[True, False], True]) # 0행은 가져오고 1행은 가져오지 않음. 열은 모두 가져옴

[[1 2 3 4]]


In [33]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
print(arr[arr > 3]) # 조건문 이용. 3보다 큰 원소 가져옴
print(arr[arr <= 2]) # 2보다 작거나 같은 원소 가져옴

[4 5 6 7 8]
[1 2]
