<a href="https://colab.research.google.com/github/JongeunKeum/python-numpy/blob/main/Section06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Section 6. N차원 배열의 병합

## 6-1. 배열에 원소 추가 및 삭제

In [2]:
# python list
arr = [1, 2, 3, 4, 5, 6, 7, 8]
arr.insert(2, 50)
print(arr)

[1, 2, 50, 3, 4, 5, 6, 7, 8]


In [3]:
# 1차원 배열 insert()
arr = np.arange(1, 9)
arr = np.insert(arr, 2, 50)
print(arr)

[ 1  2 50  3  4  5  6  7  8]


In [4]:
# 2차원 배열 insert()
arr = np.arange(1, 13).reshape(3, 4)
arr = np.insert(arr, 2, 50, axis=0)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [50 50 50 50]
 [ 9 10 11 12]]


In [5]:
arr = np.arange(1, 13).reshape(3, 4)
arr = np.insert(arr, 2, 50, axis=1)
print(arr)

[[ 1  2 50  3  4]
 [ 5  6 50  7  8]
 [ 9 10 50 11 12]]


In [7]:
arr = np.arange(1, 13).reshape(3, 4)
arr = np.insert(arr, 2, 50) # axis 값을 주지 않으면, 1차원 배열로 변환 후에 삽입함
print(arr)

[ 1  2 50  3  4  5  6  7  8  9 10 11 12]


In [9]:
# delete()
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

arr = np.delete(arr, 2, axis=0)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]


In [10]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

arr = np.delete(arr, 2, axis=1)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]]


In [11]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

arr = np.delete(arr, 2)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  4  5  6  7  8  9 10 11 12]


## 6-2. 배열 간의 병합

In [15]:
# append()
arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(13, 25).reshape(3, 4)

print(arr1)
print(arr2, end="\n\n")

# axis=0
arr3 = np.append(arr1, arr2, axis=0)
print(arr3, end="\n\n")

# axis=1
arr4 = np.append(arr1, arr2, axis=1)
print(arr4, end="\n\n")

# axis 값 없이
arr5 = np.append(arr1, arr2)
print(arr5, end="\n\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]



In [18]:
# vstack(): axis=0으로 병합, hstack(): axis=1로 병합
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(7, 13).reshape(2, 3)

arr3 = np.vstack((arr1, arr2))
print(arr3, end="\n\n")

arr4 = np.hstack((arr1, arr2))
print(arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [21]:
# concatenate()
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(7, 13).reshape(2, 3)

arr3 = np.concatenate([arr1, arr2], axis=0)
print(arr3, end="\n\n")

arr4 = np.concatenate([arr1, arr2], axis=1)
print(arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
