<a href="https://colab.research.google.com/github/JongeunKeum/python-numpy/blob/main/Section01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# Section 1. N차원 배열 생성

## 1-1. N차원 배열(ndarray) 생성하기

In [7]:
# 1차원 배열
arr = np.array([1, 2, 3])
print(arr)

# 2차원 배열
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [11]:
type([1, 2, 3])

list

In [12]:
type(arr)

numpy.ndarray

In [13]:
tpl = (4, 5, 6)
arr = np.array(tpl)
print(arr)

[4 5 6]


In [15]:
lst = [1, 2, 3]
arr = np.array(lst)
print(arr)

[1 2 3]


In [16]:
lst2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(lst2)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [19]:
# shape
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1.shape, arr2.shape) # arr1은 원소가 3개인 1차원 배열, arr2는 행이 2개, 열이 3개인 2차원 array

(3,) (2, 3)


In [20]:
# ndim 차원 표시
print(arr1.ndim, arr2.ndim)

1 2


In [22]:
# size 원소 개수
print(arr1.size, arr2.size)

3 6


## 1-2. N차원 배열의 데이터 타입

In [26]:
arr = np.array([1, 2, 3], dtype=float)
print(arr, arr.dtype)

[1. 2. 3.] float64


In [27]:
arr = np.array([1, 2, 3], dtype=int)
print(arr, arr.dtype)

[1 2 3] int64


In [28]:
arr = np.array([0, 1, 1], dtype=bool)
print(arr, arr.dtype)

[False  True  True] bool


In [31]:
arr = np.array([0, 1, 2 ,3])
print(arr, arr.dtype)

arr = arr.astype(np.float32)
print(arr, arr.dtype)

[0 1 2 3] int64
[0. 1. 2. 3.] float32


In [33]:
# 데이터 타입이 혼재하는 경우
arr = np.array([1, 2, 3.4])
print(arr, arr.dtype)
# 타입을 섞어서 넣었더니 모두 float64로 바뀌어서 출력됨

[1.  2.  3.4] float64


In [38]:
#arr = np.array([1, 2, 3.4, "string"], dtype=int)
#print(arr, arr.dtype)
# 문자열을 int로 변환할 수 없어서 에러 발생

## 1-3. 정해진 형식의 N차원 배열 생성하기

In [40]:
# np.zeros() 모든 원소가 0으로 된 배열 생성
arr = np.zeros([2, 2]) # 인자로 shape 입력
print(arr)

[[0. 0.]
 [0. 0.]]


In [41]:
# np.ones() 모든 원소가 1로 된 배열 생성
arr = np.ones([3, 5])
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [42]:
# np.full() 모든 원소가 지정된 값으로 이루어진 배열 생성
arr = np.full((2, 3), 5)
print(arr)

[[5 5 5]
 [5 5 5]]


In [51]:
# np.eye() 행을 n, 열을 m이라고 했을 때, n*m 행렬에서 대각선 원소가 1인 배열 생성(n값만 주면 정방행렬 생성)
arr = np.eye(3, 4)
print("arr")
print(arr)

arr2 = np.eye(3, 4, k=1) # k값은 대각원소의 발생지점 지정 가능
print("arr2")
print(arr2)

arr3 = np.eye(3, 4, k=-1)
print("arr3")
print(arr3)

arr
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
arr2
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
arr3
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [54]:
# 지정된 행렬과 동일한 shape을 갖도록 함
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# np.zeros_like()
arr_z = np.zeros_like(arr)
print("zeros_like")
print(arr_z)

# np.ones_like()
arr_o = np.ones_like(arr)
print("ones_like")
print(arr_o)

# np.full_like()
arr_f = np.full_like(arr, 9)
print("full_like")
print(arr_f)

zeros_like
[[0 0 0]
 [0 0 0]]
ones_like
[[1 1 1]
 [1 1 1]]
full_like
[[9 9 9]
 [9 9 9]]
