<a href="https://colab.research.google.com/github/JongeunKeum/python-numpy/blob/main/Section02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Section 2. N차원 배열 인덱싱

## 2-1. 배열의 index 접근하기

In [3]:
# 1차원 배열
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(arr[3])
print(arr[1])
print(arr[-1])
print(arr[-3])

3
1
9
7


In [11]:
# 2차원 배열 인덱싱
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print(arr, arr.shape, arr.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 2


In [13]:
print(arr[0]) # 0행에 해당하는 값 전부

[1 2 3 4]


In [15]:
print(arr[0][3]) # 0행 3열
print(arr[0, 3])

4
4


In [23]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[3:8]) # 3부터 8 미만까지
print(arr[3:]) # 3부터 끝까지
print(arr[:7]) # 처음부터 7 미만까지
print(arr[:-1])

[3 4 5 6 7]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8]


In [25]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print(arr[0, :]) # 0행 모든 열
print(arr[:, 1]) # 모든 행 1열

[1 2 3 4]
[ 2  6 10]


In [27]:
print(arr[:3, :])
print(arr[:2, 2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]
