<a href="https://colab.research.google.com/github/JongeunKeum/python-numpy/blob/main/Section04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Section 4. N차원 배열 정렬

## 4-1. 1차원 배열의 정렬

In [2]:
arr = np.random.randint(10, size=10)
print(arr)

[5 4 6 4 0 0 8 5 7 6]


In [5]:
print(np.sort(arr))         # 오름차순
print(np.sort(arr)[::-1])   # 내림차순
# 이런 방법은 원본 배열이 변경되지 않음

[0 0 4 4 5 5 6 6 7 8]
[8 7 6 6 5 5 4 4 0 0]


In [7]:
# arr = np.sort(arr)    # 원본 배열 변경
arr.sort()            # 원본 배열 변경
print(arr)

[0 0 4 4 5 5 6 6 7 8]
