<a href="https://colab.research.google.com/github/JongeunKeum/python-numpy/blob/main/Section01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# Section 1. N차원 배열 생성

## 1-1. N차원 배열(ndarray) 생성하기

In [7]:
# 1차원 배열
arr = np.array([1, 2, 3])
print(arr)

# 2차원 배열
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [11]:
type([1, 2, 3])

list

In [12]:
type(arr)

numpy.ndarray

In [13]:
tpl = (4, 5, 6)
arr = np.array(tpl)
print(arr)

[4 5 6]


In [15]:
lst = [1, 2, 3]
arr = np.array(lst)
print(arr)

[1 2 3]


In [16]:
lst2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(lst2)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [19]:
# shape
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1.shape, arr2.shape) # arr1은 원소가 3개인 1차원 배열, arr2는 행이 2개, 열이 3개인 2차원 array

(3,) (2, 3)


In [20]:
# ndim 차원 표시
print(arr1.ndim, arr2.ndim)

1 2


In [22]:
# size 원소 개수
print(arr1.size, arr2.size)

3 6


## 1-2. N차원 배열의 데이터 타입

In [26]:
arr = np.array([1, 2, 3], dtype=float)
print(arr, arr.dtype)

[1. 2. 3.] float64


In [27]:
arr = np.array([1, 2, 3], dtype=int)
print(arr, arr.dtype)

[1 2 3] int64


In [28]:
arr = np.array([0, 1, 1], dtype=bool)
print(arr, arr.dtype)

[False  True  True] bool


In [31]:
arr = np.array([0, 1, 2 ,3])
print(arr, arr.dtype)

arr = arr.astype(np.float32)
print(arr, arr.dtype)

[0 1 2 3] int64
[0. 1. 2. 3.] float32


In [33]:
# 데이터 타입이 혼재하는 경우
arr = np.array([1, 2, 3.4])
print(arr, arr.dtype)
# 타입을 섞어서 넣었더니 모두 float64로 바뀌어서 출력됨

[1.  2.  3.4] float64


In [36]:
arr = np.array([1, 2, 3.4, "string"], dtype=int)
print(arr, arr.dtype)
# 문자열을 int로 변환할 수 없어서 에러 발생

ValueError: ignored