<a href="https://colab.research.google.com/github/JongeunKeum/python-numpy/blob/main/Section05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Section 5. N차원 배열의 형태 변경

## 5-1. 배열의 형태 변경 1: reshape()

In [3]:
arr = np.arange(12)
print(arr, arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 1


In [5]:
arr = arr.reshape((3, 4))   # 원소의 개수가 맞아야 함
print(arr, arr.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2


In [7]:
arr = arr.reshape((2, 3, 2))
print(arr, arr.ndim)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 3


In [8]:
arr = arr.reshape((2, 2, 1, 3))
print(arr, arr.ndim)

[[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]] 4


### Curse of Dimensionality (차원의 저주)

차원이 증가하면서 학습 데이터 수가 차원의 수보다 적어지면서 모델의 성능이 저하되는 현상

## 5-2. 배열의 형태 변경 2: resize(0, ravel()

In [9]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
# resize() reshape()과 동일하지만 원본 배열을 변경시킴
arr.resize(3, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
# ravel() 1차원 배열로 변경시킴
arr = arr.ravel()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
arr = np.arange(1, 13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [17]:
arr = arr.reshape(3, -1)  # -1을 입력하면 자동으로 계산이 됨(12개에 맞춰서 자동으로 4가 들어가게 됨)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
arr = arr.reshape(3, 2, -1)   # -1은 한 번만 써야 함
print(arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


## 5-3. 배열의 형태 변경 3: expand_dims(), squeeze()

In [40]:
arr = np.array([1, 2])
print(arr, arr.shape)

# expand_dims() 입력한 axis 값을 기준으로 차원을 추가함
arr1 = np.expand_dims(arr, axis=0)
print(arr1, arr1.shape)

arr2 = np.expand_dims(arr, axis=1)
print(arr2, arr2.shape)

[1 2] (2,)
[[1 2]] (1, 2)
[[1]
 [2]] (2, 1)


In [44]:
# squeeze() 배열의 축을 하나 제거하여 차원을 축소함
arr = np.array([[1, 2]])
print(arr, arr.shape, arr.ndim)

arr = np.squeeze(arr, axis=0)
print(arr, arr.shape, arr.ndim)

[[1 2]] (1, 2) 2
[1 2] (2,) 1


In [45]:
arr = np.array([[[1],
                 [2],
                 [3]]])
print(arr, arr.shape, arr.ndim)

arr = np.squeeze(arr, axis=0)
print(arr, arr.shape, arr.ndim)

[[[1]
  [2]
  [3]]] (1, 3, 1) 3
[[1]
 [2]
 [3]] (3, 1) 2


In [46]:
arr = np.array([[[1, 2, 3]]])
print(arr, arr.shape, arr.ndim)

arr = np.squeeze(arr, axis=1)
print(arr, arr.shape, arr.ndim)

[[[1 2 3]]] (1, 1, 3) 3
[[1 2 3]] (1, 3) 2


In [49]:
arr = np.array([[[1, 2, 3]]])
print(arr, arr.shape, arr.ndim)

arr = np.squeeze(arr)
print(arr, arr.shape, arr.ndim)

[[[1 2 3]]] (1, 1, 3) 3
[1 2 3] (3,) 1
